export const PRODUCTS = {
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  DECREMENT_PRODUCT_INVENTORY: 'DECREMENT_PRODUCT_INVENTORY'
};

export const CART = {
  INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
  PUSH_PRODUCT_TO_CART: 'PUSH_PRODUCT_TO_CART',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS'
};
